---
title: 'Course Project: Shiny Application and Reproducible Pitch'
author: "Javier Ng"
date: "August 18, 2018"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction

This is for the Coursera course: Developing Data Products as part of the Coursera Data Science Specialization.

Instructions:

*  Write a shiny application with associated supporting documentation. The documentation should be thought of as whatever a user will need to get started using your application.
*  Deploy the application on Rstudio's shiny server
*  Share the application link by pasting it into the provided text box
*  Share your server.R and ui.R code on github

## How to Use Application

Using the data provided by Galton Families dataset, we fit a linear model to predict a child's height based on the gender and parent's average height.

The application is running on (https://javierngkh.shinyapps.io/week4courseradataprdt/)

ui.R, and Server.R Code are on my github repo: (https://github.com/XavierFontane/Course-Project-Shiny-Application-and-Reproducible-Pitch)

## Galton Familities Data Set

The data used in the app comes from the GaltonFamilies dataset, under the package `HistData`

```{R}
library(HistData)
data("GaltonFamilies")
summary(GaltonFamilies)
```

## Plot

```{R}
plot(jitter(GaltonFamilies$childHeight) ~ GaltonFamilies$midparentHeight,xlab="Average Height of the Parents (in inches)",ylab="Height of the Child (in inches)",main="Scatterplot of Galton Family Data",pch=19,frame.plot=FALSE,col=ifelse(GaltonFamilies$gender=="female", "gold", "red"))
legend(65,80,pch=c(19,19),col=c("gold","red"),c("female", "male"),bty="o",cex=.8)
```

